apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connor-birthday
  namespace: connor-birthday
spec:
  ingressClassName: traefik
  rules:
  - host: connor-birthday.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: connor-birthday
            port:
              number: 80
