apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: connor-birthday

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- cloudflare.yaml
- aws-secret-store.yaml
- external-secret-tunnel.yaml
- external-secret-dockerhub.yaml
- create-docker-registry-secret-job.yaml
