apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-bench
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - storage.yaml
  - cronjob.yaml
  # Obsidian reporting
  - aws-secret-store.yaml
  - external-secret-obsidian.yaml
  - configmap-reporter.yaml
  - cronjob-reporter.yaml

labels:
- pairs:
    app.kubernetes.io/name: kube-bench
    app.kubernetes.io/part-of: security
    app.kubernetes.io/managed-by: kustomize
