apiVersion: v1
kind: Service
metadata:
  name: agent-app-security
  namespace: zi-agents
  labels:
    app.kubernetes.io/name: agent-app-security
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: zi-agents
spec:
  selector:
    app: agent-app-security
  ports:
    - port: 8000
      targetPort: http
      name: http
