apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-config
  namespace: ${{ values.name }}
  labels:
    app: ${{ values.name }}
data:
  APP_NAME: "${{ values.name }}"
  APP_ENV: "production"
  GPU_MEMORY_REQUIRED: "${{ values.gpuMemoryRequired }}"
