apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.name }}
resources:
  - namespace.yaml
  - configmap.yaml
{%- if values.enableSecrets %}
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret.yaml
{%- endif %}
  - storage.yaml
  - deployment-gpu.yaml
  - service.yaml
  - ingress.yaml
  - catalog-info.yaml
