apiVersion: v1
kind: Service
metadata:
  name: exo
  namespace: exo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 52415
      protocol: TCP
      name: http
---
apiVersion: v1
kind: Endpoints
metadata:
  name: exo
  namespace: exo
subsets:
  - addresses:
      - ip: 10.85.30.15
    ports:
      - port: 52415
        protocol: TCP
        name: http
