apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n3xis
  namespace: n3xis
  labels:
    app: n3xis
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - shopflor.n3xis.com
      secretName: n3xis-tls
  rules:
    - host: shopflor.n3xis.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n3xis
                port:
                  number: 80
