apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: langfuse
resources:
  - namespace.yaml
  - helm-repository.yaml
  - secret-store.yaml
  - external-secret.yaml
  - release.yaml
  - ingress.yaml
