apiVersion: v1
kind: ConfigMap
metadata:
  name: zeroed-config
  namespace: zeroed
data:
  CORS_ORIGINS: "https://zeroed.landryzetam.net,http://localhost:3000"
  METHOD_ENVIRONMENT: "production"
  LOG_LEVEL: "info"
