apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zeroed
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-store.yaml
  - external-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - services.yaml
  - ingress.yaml
