apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: social-marketing-agent
resources:
  - ../../base/social-marketing-agent
  - aws-credentials-secret.yaml
  - dockerhub-secret.yaml
  - create-docker-registry-secret-job.yaml
