apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: social-marketing-agent

resources:
  - namespace.yaml
  - configmap.yaml
  - secret-store.yaml
  - external-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - cronjob.yaml
  - service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
