apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
resources:
  - namespace.yaml
  - storage.yaml
  - smb-storage.yaml
  - redis.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
  - secret-store.yaml
  - external-secret-postgres.yaml
  - external-secret-paperless.yaml
  - external-secret-smb.yaml
