apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thornus
  namespace: thornus
  labels:
    app: thornus
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns01
spec:
  tls:
    - hosts:
        - thornus.landryzetam.net
      secretName: thornus-tls
  rules:
    - host: thornus.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thornus-frontend-service
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: thornus-backend-service
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: thornus-backend-service
                port:
                  number: 8000
          - path: /ready
            pathType: Exact
            backend:
              service:
                name: thornus-backend-service
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: thornus-backend-service
                port:
                  number: 8000
          - path: /webhooks
            pathType: Prefix
            backend:
              service:
                name: thornus-backend-service
                port:
                  number: 8000
