apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - letsencrypt-staging.yaml
  - letsencrypt-production.yaml
  - letsencrypt-dns01.yaml
  - aws-secret-store.yaml
  - external-secret-cloudflare.yaml
