apiVersion: v1
kind: ConfigMap
metadata:
  name: ${{ values.name }}-config
  namespace: ${{ values.name }}
  labels:
    app.kubernetes.io/name: ${{ values.name }}
data:
  # Frontend config
  NEXT_PUBLIC_API_URL: "https://${{ values.frontendHostname }}/api"
  NEXT_PUBLIC_APP_NAME: "${{ values.name }}"

  # Backend config
  APP_NAME: "${{ values.name }}"
  APP_ENV: "production"
  CORS_ORIGINS: "https://${{ values.frontendHostname }}"
