apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${{ values.name }}
resources:
  - namespace.yaml
  - configmap.yaml
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret.yaml
{%- if values.enableStorage %}
  - storage.yaml
{%- endif %}
  - deployment-frontend.yaml
  - deployment-backend.yaml
  - service-frontend.yaml
  - service-backend.yaml
  - ingress.yaml
  - catalog-info.yaml
