apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nick-brothers-api
  namespace: nick-brothers
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
    - host: nnb-api.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8000
  tls:
    - hosts:
        - nnb-api.landryzetam.net
      secretName: nnb-api-landryzetam-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nick-brothers-dashboard
  namespace: nick-brothers
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
    - host: nnb.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 3000
  tls:
    - hosts:
        - nnb.landryzetam.net
      secretName: nnb-dashboard-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nick-brothers-website
  namespace: nick-brothers
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  rules:
    - host: nnb-site.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: website
                port:
                  number: 3000
  tls:
    - hosts:
        - nnb-site.landryzetam.net
      secretName: nnb-site-tls
