apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - external-secrets
  - renovate
  - nfs-storage
  - smb-csi
  - gpu-operator
  - k8s-backup
  - system-tuning
  - cloudnative-pg
  - unifi-data
