apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: umami

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret-store.yaml
  - external-secret-postgres.yaml
  - database-init-job.yaml

labels:
  - pairs:
      app.kubernetes.io/name: umami
      app.kubernetes.io/instance: production
      app.kubernetes.io/component: analytics
      app.kubernetes.io/part-of: blog
