apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audio-compressor
resources:
  - ../../base/audio-compressor
  - aws-credentials-secret.yaml
  - dockerhub-credentials-secret.yaml
