apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubescape

resources:
  - ../../base/kubescape-operator
  - aws-credentials-secret.yaml
  - dockerhub-secret.yaml

patchesStrategicMerge:
  - patch-nodeagent-exclusion.yaml
