apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: meal-tracker

resources:
  - namespace.yaml
  - configmap.yaml
  - secretstore.yaml
  - external-secret.yaml
  - external-secret-dockerhub.yaml
  - deployment.yaml
  - dashboard.yaml
