apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autobots
  namespace: zi
  labels:
    app: autobots
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/name: autobots
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-dns01"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - autobots.landryzetam.net
      secretName: autobots-tls-cert
  rules:
    - host: autobots.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: autobots
                port:
                  number: 8000
