apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zi
  namespace: zi
  labels:
    app: zi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - zi.landryzetam.net
      secretName: zi-tls-cert
  rules:
    - host: zi.landryzetam.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zi
                port:
                  number: 8080
