apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secretstore.yaml
  - external-secret.yaml
  - external-secret-dockerhub.yaml
  - gateway.yaml
  - recorder.yaml
  - replay.yaml
  - redis.yaml
  - storage.yaml
  - ingress.yaml
  - backfill.yaml
