apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audio-compressor
resources:
  - namespace.yaml
  - aws-secret-store.yaml
  - external-secret-sftp.yaml
  - external-secret-gpustack.yaml
  - external-secret-summarizer.yaml
  - external-secret-obsidian.yaml
  - create-docker-registry-secret-job.yaml
  - rbac.yaml
  - storage.yaml
  - configmap-transcriber.yaml
  - configmap-summarizer.yaml
  - configmap-publisher.yaml
  - configmap-publisher-script.yaml
  - configmap-summarizer-script.yaml
  - configmap-daily-diary.yaml
  - configmap-daily-diary-script.yaml
  - cronjob.yaml
  - cronjob-transcriber.yaml
  - cronjob-publisher.yaml
  - cronjob-summarizer.yaml
  - cronjob-daily-diary.yaml
