apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audio-compressor
resources:
  - namespace.yaml
  - aws-secret-store.yaml
  - external-secret-sftp.yaml
  - external-secret-dockerhub.yaml
  - create-docker-registry-secret-job.yaml
  - rbac.yaml
  - cronjob.yaml
