apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whisperx
resources:
  - namespace.yaml
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret-hf.yaml
  - storage.yaml
  - deployment-api.yaml
  - service.yaml
  - ingress.yaml
  # Batch processing (disabled - using API instead)
  # - configmap-processor.yaml
  # - job-processor.yaml
