apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: whisperx
resources:
  - namespace.yaml
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret-hf.yaml
  - configmap-processor.yaml
  - job-processor.yaml
