{%- if values.enableIngress %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.appName }}
  namespace: ${{ values.appName }}
  labels:
    app.kubernetes.io/name: ${{ values.appName }}
    app.kubernetes.io/component: ${{ values.component }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${{ values.hostname }}
      secretName: ${{ values.appName }}-tls
  rules:
    - host: ${{ values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.appName }}
                port:
                  number: ${{ values.port }}
{%- endif %}
