apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ${{ values.appName }}

resources:
  - namespace.yaml
{%- if values.enableSecrets %}
  - secretstore.yaml
  - external-secret.yaml
{%- endif %}
{%- if values.enableRedis %}
  - redis.yaml
{%- endif %}
{%- if values.enableStorage %}
  - storage.yaml
{%- endif %}
  - deployment.yaml
  - service.yaml
{%- if values.enableIngress %}
  - ingress.yaml
{%- endif %}

labels:
  - pairs:
      app.kubernetes.io/name: ${{ values.appName }}
      app.kubernetes.io/instance: production
      app.kubernetes.io/component: ${{ values.component }}
      app.kubernetes.io/part-of: ${{ values.partOf }}
