apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zeroed
resources:
  - ../../base/zeroed
  - aws-credentials-secret.yaml
  - dockerhub-secret.yaml
  - create-docker-registry-secret-job.yaml
