apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sftp-server
resources:
  - namespace.yaml
  - aws-credentials-secret.yaml
  - aws-secret-store.yaml
  - external-secret-sftp-creds.yaml
  - unifi-pvc.yaml
  - audio-compressed-pvc.yaml
  - audio-transcript-pvc.yaml
  - host-keys-pvc.yaml
  - deployment.yaml
  - service.yaml
