apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: postgres-recovery
resources:
  - namespace.yaml
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret-admin.yaml
  - backup-pv.yaml
  - backup-pvc.yaml
  - statefulset.yaml
  - service.yaml
  # - restore-job.yaml  # Manual job - run only when needed with updated backup path
  - verification-configmap.yaml
