apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: family-manager

resources:
  - namespace.yaml
  - secretstore.yaml
  - external-secret.yaml
  - external-secret-dockerhub.yaml
  - redis.yaml
  - deployment.yaml
  - deployment-bot.yaml
  - service.yaml
  - ingress.yaml
  - cloudflare.yaml

labels:
  - pairs:
      app.kubernetes.io/name: family-manager
      app.kubernetes.io/instance: production
      app.kubernetes.io/component: webhook
      app.kubernetes.io/part-of: family-manager
