apiVersion: v1
kind: Service
metadata:
  name: family-manager-webhook
  namespace: family-manager
spec:
  selector:
    app: family-manager-webhook
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
