apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    app: ${{ values.name }}
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ${{ values.hostname }}
      secretName: ${{ values.name }}-tls
  rules:
    - host: ${{ values.hostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.name }}
                port:
                  number: ${{ values.port }}
