apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-trades-config
  labels:
    app: quantum-trades
data:
  # CORS origins
  CORS_ORIGINS: '["https://quantum.landryzetam.net"]'

  # Rate limiting configuration
  RATE_LIMIT_CALLS_PER_MINUTE: "5"
