apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quantum-trades
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-store.yaml
  - external-secret.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - signals-deployment.yaml
  - technicals-deployment.yaml
  - strategies-deployment.yaml
  - backtesting-deployment.yaml
  - services.yaml
  - ingress.yaml
