apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: claude-code

resources:
  - namespace.yaml
  - aws-secret-store.yaml
  - external-secret-dockerhub.yaml
  - external-secret-oauth.yaml
  - configmap-ssh.yaml
  - deployment.yaml
  - service.yaml
