apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubescape

resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  # Obsidian reporting
  - aws-secret-store.yaml
  - external-secret-obsidian.yaml
  - configmap-reporter.yaml
  - rbac-reporter.yaml
  - cronjob-reporter.yaml

labels:
- pairs:
    app.kubernetes.io/name: kubescape-operator
    app.kubernetes.io/part-of: security
    app.kubernetes.io/managed-by: kustomize
