apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mcp-gateway

resources:
  - namespace.yaml
  - secret-store.yaml
  - external-secret-github.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - cloudflare.yaml
  - cloudflare-secret.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: mcp-gateway
    app.kubernetes.io/managed-by: kustomize
