apiVersion: v1
kind: Service
metadata:
  name: oura-agent
  namespace: oura-agent
  labels:
    app: oura-agent
spec:
  type: ClusterIP
  selector:
    app: oura-agent
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
