---
# apps/base/pgadmin/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:9.9.0
        ports:
        - containerPort: 80
          protocol: TCP
        envFrom:
        - configMapRef:
            name: pgadmin-config
        - secretRef:
            name: pgadmin-secret
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin
        - name: servers-config
          mountPath: /pgadmin4/servers.json
          subPath: servers.json
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-data
      - name: servers-config
        configMap:
          name: pgadmin-config
          items:
          - key: servers.json
            path: servers.json

# ---
# # apps/base/pgadmin/deployment.yaml
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: pgadmin
#   namespace: pgadmin
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: pgadmin
#   template:
#     metadata:
#       labels:
#         app: pgadmin
#     spec:
#       containers:
#       - name: pgadmin
#         image: dpage/pgadmin4:9.6.0
#         ports:
#         - containerPort: 80
#           protocol: TCP
#         envFrom:
#         - configMapRef:
#             name: pgadmin-config
#         - secretRef:
#             name: pgadmin-secret
#         volumeMounts:
#         - name: pgadmin-data
#           mountPath: /var/lib/pgadmin
#         resources:
#           requests:
#             memory: "256Mi"
#             cpu: "250m"
#           limits:
#             memory: "512Mi"
#             cpu: "500m"
#       volumes:
#       - name: pgadmin-data
#         # emptyDir: {}
#         persistentVolumeClaim:  # Using PVC instead of emptyDir
#           claimName: pgadmin-data
