# apps/base/pgadmin/external-secret-config.yaml
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-config-external-secret
  namespace: pgadmin
spec:
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
    - secretKey: PGADMIN_DEFAULT_EMAIL
      remoteRef:
        key: pgadmin/admin
        property: email
  refreshInterval: 1h
