# apps/base/pgadmin/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pgadmin
resources:
  - namespace.yaml
  - configmap.yaml
  - storage.yaml
  - aws-credentials-secret.yaml
  - secret-store.yaml
  - external-secret-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml