apiVersion: v1
kind: Service
metadata:
  name: phoenix-backend-service
  namespace: phoenix
  labels:
    app: phoenix-backend
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: phoenix-backend
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-frontend-service
  namespace: phoenix
  labels:
    app: phoenix-frontend
    component: web
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: phoenix-frontend